title: Enterprize Training Update
author: Thomas Rose
email: thomaswrose@gmail.com
description: > # Enterprize training platform test site
Theme: Minima

# social links

github_username:  Thomaswrose

show_excerpts: true
