title: Enterprize Training Testing Site
author: Thomas Rose
email: thomaswrose@gmail.com
description: > # This is a test site for an online Saas product user training site

### social links
github_username:  thomaswrose

show_excerpts: true
Theme: minima
